# Generated by Django 5.0.2 on 2024-08-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_inventory_flag_item_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='inventory_flag',
            new_name='inventory_managed',
        ),
    ]
