# Generated by Django 5.0.2 on 2024-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory_flag_item_inventory_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='extra_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='extra_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
